-- AlterTable
ALTER TABLE "User" ADD COLUMN     "OTP" TEXT,
ADD COLUMN     "OTPExpires" TIMESTAMP(3),
ADD COLUMN     "isVerified" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "otpAttempts" INTEGER NOT NULL DEFAULT 0;
